import { Button, LineEdit, ScrollView, VerticalBox, HorizontalBox, TextEdit, StyleMetrics, AboutSlint, Palette } from "std-widgets.slint";

export component AppWindow inherits Window {
    title: "Cous Patcher";
    min-width: 560px;
    min-height: 420px;
    preferred-width: 600px;
    preferred-height: 480px;
    background: #363636;

    // Callbacks into C++
    callback browse-clicked();
    callback patch-clicked(string, string);

    // Properties set from C++
    in-out property <string> app-path;
    in-out property <string> fake-name;
    in property <string> log-text;
    in-out property <bool>   patching;

    VerticalBox {
        padding: 26px;
        spacing: 16px;

        Text {
            text: "Target .app";
            font-size: 20px;
            color: #acacac;
        }

        HorizontalBox {
            padding: 4px;
            spacing: 12px;

            LineEdit {
                placeholder-text: "/Applications/Steam.app";
                text <=> root.app-path;
                enabled: !root.patching;
                horizontal-stretch: 1;
            }

            Button {
                text: "Browse";
                enabled: !root.patching;
                clicked => { root.browse-clicked(); }
            }
        }

        Text {
            text: "Fake process name";
            font-size: 20px;
            color: #acacac;
        }

        LineEdit {
            placeholder-text: "not-steam";
            text <=> root.fake-name;
            enabled: !root.patching;
        }

        Button {
            colorize-icon: true;
            text: root.patching ? "Patching..." : "Patch";
            enabled: !root.patching && root.app-path != "" && root.fake-name != "";
            clicked => { root.patch-clicked(root.app-path, root.fake-name); }
        }

        Text {
            text: "Log";
            font-size: 16px;
            color: #acacac;
        }

        Rectangle {
            border-color: #454545;
            background: #222;
            border-width: 2px;
            border-radius: 16px;
            vertical-stretch: 1;
            clip: true;

            ScrollView {
                TextEdit {
                    text: root.log-text;
                    read-only: true;
                    wrap: word-wrap;
                    font-family: "monospace";
                    font-size: 16px;

                    width: parent.width;
                    height: parent.height;
                }
            }
        }
    }
}
